name: snackstack
description: Flutter package for pretty snackbars
version: 2.0.0
repository: https://github.com/justjew/snackstack

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
